flowchart LR
    StripClub["StripClub"]
    GasStation["GasStation"]
    JewelryStore["JewelryStore"]
    Bar["Bar"]
    Casino["Casino"]
    LostLoveParish["LostLoveParish"]
    ForbiddenRoseChapel["ForbiddenRoseChapel"]
    LastGoodbyeSanctuary["LastGoodbyeSanctuary"]
    SecretsOfTheSoulChurch["SecretsOfTheSoulChurch"]
    FinalDestinyCathedral["FinalDestinyCathedral"]

    StripClub ---|"Medium"| GasStation
    StripClub ---|"Near"| Bar
    GasStation ---|"Medium"| JewelryStore
    GasStation ---|"Near"| Bar
    GasStation ---|"Near"| Casino
    Bar ---|"Near"| Casino
    JewelryStore ---|"Medium"| Casino
    JewelryStore ---|"Medium"| LostLoveParish
    JewelryStore ---|"Medium"| ForbiddenRoseChapel
    JewelryStore ---|"Medium"| LastGoodbyeSanctuary
    JewelryStore ---|"Far"| SecretsOfTheSoulChurch
    JewelryStore ---|"Far"| FinalDestinyCathedral
    LostLoveParish ---|"Near"| ForbiddenRoseChapel
    ForbiddenRoseChapel ---|"Near"| LastGoodbyeSanctuary
    LastGoodbyeSanctuary ---|"Near"| SecretsOfTheSoulChurch
    SecretsOfTheSoulChurch ---|"Near"| FinalDestinyCathedral
    FinalDestinyCathedral ---|"Medium"| LostLoveParish
